RegisterNetEvent("VehicleDespawner:notification")
AddEventHandler("VehicleDespawner:notification", function(msg)
    SetNotificationTextEntry('STRING')
    AddTextComponentSubstringPlayerName(msg)
    return DrawNotification(false, true)
end)
